/**
 * Manual Zod schemas for the integrations, invoice-export, and marketing draft endpoints.
 * (Not generated by orval — added alongside the generated files.)
 */
import * as zod from "zod";

export const IntegrationProviderStatus = zod.object({
  connected: zod.boolean(),
  connectedAt: zod.string().nullable(),
  lastSyncAt: zod.string().nullable(),
  configured: zod.boolean(),
});

export const GetIntegrationStatusResponse = zod.object({
  google: IntegrationProviderStatus,
  quickbooks: IntegrationProviderStatus,
  xero: IntegrationProviderStatus,
});

export const DisconnectIntegrationParams = zod.object({
  provider: zod.enum(["google", "quickbooks", "xero"]),
});

export const ExportInvoiceParams = zod.object({
  id: zod.number().int(),
  target: zod.enum(["quickbooks", "xero"]),
});

export const ExportInvoiceResponse = zod.object({
  ok: zod.boolean(),
  externalId: zod.string(),
  docNumber: zod.string().optional(),
  invoiceNumber: zod.string().optional(),
  url: zod.string().optional(),
});

// ── Marketing Drafts ─────────────────────────────────────────────────────────

export const MarketingDraftType = zod.enum(["review_request", "followup"]);
export const MarketingDraftStatus = zod.enum(["pending", "approved", "dismissed"]);

export const MarketingDraft = zod.object({
  id: zod.number().int(),
  jobId: zod.number().int().nullable(),
  jobTitle: zod.string(),
  clientName: zod.string(),
  clientPhone: zod.string().nullable(),
  companyName: zod.string(),
  type: MarketingDraftType,
  status: MarketingDraftStatus,
  draftMessage: zod.string().nullable(),
  editedMessage: zod.string().nullable(),
  createdAt: zod.string(),
});

export const ListMarketingDraftsResponse = zod.array(MarketingDraft);

export const GenerateMarketingDraftsBody = zod.object({
  jobId: zod.number().int(),
  jobTitle: zod.string(),
  clientName: zod.string(),
  clientPhone: zod.string().optional(),
  companyName: zod.string(),
});

export const GenerateMarketingDraftsResponse = zod.array(MarketingDraft);

export const UpdateMarketingDraftParams = zod.object({
  id: zod.number().int(),
});

export const UpdateMarketingDraftBody = zod.object({
  editedMessage: zod.string().optional(),
  status: MarketingDraftStatus.optional(),
});

export const UpdateMarketingDraftResponse = MarketingDraft;

export const ApproveMarketingDraftParams = zod.object({
  id: zod.number().int(),
});

export const ApproveMarketingDraftResponse = MarketingDraft;

export const DismissMarketingDraftParams = zod.object({
  id: zod.number().int(),
});

export const DismissMarketingDraftResponse = MarketingDraft;

export const DeleteMarketingDraftParams = zod.object({
  id: zod.number().int(),
});
