/**
 * Manual Zod schemas for the integrations & invoice-export endpoints.
 * (Not generated by orval — added alongside the generated files.)
 */
import * as zod from "zod";

export const IntegrationProviderStatus = zod.object({
  connected: zod.boolean(),
  connectedAt: zod.string().nullable(),
  lastSyncAt: zod.string().nullable(),
  configured: zod.boolean(),
});

export const GetIntegrationStatusResponse = zod.object({
  google: IntegrationProviderStatus,
  quickbooks: IntegrationProviderStatus,
  xero: IntegrationProviderStatus,
});

export const DisconnectIntegrationParams = zod.object({
  provider: zod.enum(["google", "quickbooks", "xero"]),
});

export const ExportInvoiceParams = zod.object({
  id: zod.number().int(),
  target: zod.enum(["quickbooks", "xero"]),
});

export const ExportInvoiceResponse = zod.object({
  ok: zod.boolean(),
  externalId: zod.string(),
  docNumber: zod.string().optional(),
  invoiceNumber: zod.string().optional(),
  url: zod.string().optional(),
});
