/**
 * React Query hooks for integrations & invoice export endpoints.
 * (Manual — not generated by orval.)
 */
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { customFetch } from "./custom-fetch";

// ── Types ────────────────────────────────────────────────────────────────────

export interface IntegrationProviderStatus {
  connected: boolean;
  connectedAt: string | null;
  lastSyncAt: string | null;
  configured: boolean;
}

export interface IntegrationStatus {
  google: IntegrationProviderStatus;
  quickbooks: IntegrationProviderStatus;
  xero: IntegrationProviderStatus;
}

export interface ExportResult {
  ok: boolean;
  externalId: string;
  docNumber?: string;
  invoiceNumber?: string;
  url?: string;
}

// ── Query keys ───────────────────────────────────────────────────────────────

export const getIntegrationStatusQueryKey = () => ["/api/integrations/status"] as const;

// ── Hooks ────────────────────────────────────────────────────────────────────

/** Fetch connection status for all three providers. */
export function useGetIntegrationStatus() {
  return useQuery<IntegrationStatus>({
    queryKey: getIntegrationStatusQueryKey(),
    queryFn: ({ signal }) =>
      customFetch<IntegrationStatus>("/api/integrations/status", { method: "GET", signal }),
  });
}

/** Disconnect a provider by deleting its stored tokens. */
export function useDisconnectIntegration() {
  const qc = useQueryClient();
  return useMutation<{ ok: boolean }, Error, { provider: "google" | "quickbooks" | "xero" }>({
    mutationFn: ({ provider }) =>
      customFetch<{ ok: boolean }>(`/api/integrations/${provider}`, { method: "DELETE" }),
    onSuccess: () => {
      qc.invalidateQueries({ queryKey: getIntegrationStatusQueryKey() });
    },
  });
}

/** Export an invoice to QuickBooks or Xero. */
export function useExportInvoice() {
  return useMutation<ExportResult, Error, { id: number; target: "quickbooks" | "xero" }>({
    mutationFn: ({ id, target }) =>
      customFetch<ExportResult>(`/api/invoices/${id}/export/${target}`, { method: "POST" }),
  });
}
